SJDToolHire.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SJDToolHire.Domain.Abstract;

namespace SJDToolHire.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IToolRepository repository;

        public NavController(IToolRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Tools
                                             .Select(x => x.Category)
                                             .Distinct()
                                             .OrderBy(x => x);
            return PartialView("FlexMenu", categories);
        }
    }
}

SJDToolHire.WebUI/Controllers/ToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SJDToolHire.Domain.Abstract;
using SJDToolHire.Domain.Entities;
using SJDToolHire.WebUI.Models;

namespace SJDToolHire.WebUI.Controllers
{
    public class ToolController : Controller
    {
        private IToolRepository repository;
        public int PageSize = 4;

        public ToolController(IToolRepository toolRepository)
        {
            this.repository = toolRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ToolsListViewModel model = new ToolsListViewModel
            {
                Tools = repository.Tools
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Tools.Count() : repository.Tools.Where(e => e.Category == category).Count() 
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

SJDToolHire.WebUI/Views/Shared/ToolSummary.cshtml
@model SJDToolHire.Domain.Entities.Tool

<div class="well col-md-12 col-md-offset-0" style="background: #474744; border: none; padding-left: 10px; padding-right: 10px; padding-top: 0px; padding-bottom: 0px;">
    <div class="panel panel-default" style="border: none; background-color: #EBEBEB; padding-left: 0px; padding-right: 0px">
        <div class="panel-heading" style="background: #474744; border: none">
            <span>
                <span class="lead" style="padding-left: 0px; color: white; background-color: #474744;">
                    <strong>@Model.Name</strong>
                </span>
                <span class="pull-right label label-warning" style="font-size:large">
                    @Model.Rate.ToString("c") per day
                </span>
            </span>
        </div>
        <div class="panel-body">
            <div style="padding-left: 20px; color:black">
                <p><strong>Description: </strong>@Model.Description</p>
                <p><strong>Power Supply: </strong>@Model.Power</p>
                <p><strong>Weight:</strong> @Model.Weight</p>
            </div>
            <div style="padding-left: 20px">
                <img src='@Url.Content(@Model.ImageUrl)' class="img-thumbnail" style="width:150px; height: auto" />
            </div>
        </div>
        <div class="panel-footer" style="height:55px; color: #B0B0B0; border: none; background: #474744; ">
            <span style="padding-left: 0px; font-size:larger; font-style:italic">
                <strong>Category: </strong>@Model.Category
            </span>
            <span class="pull-right">
                @using (Html.BeginForm("AddToCart", "Cart"))
                {

                    @Html.HiddenFor(x => x.ProductID)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Add to basket" />
                }
            </span>
        </div>
    </div>
</div>

SJDToolHire.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/signin.css" rel="stylesheet" />
    <script src="∼/Scripts/jquery-1.9.1.js"></script>
    <script src="∼/Scripts/jquery.validate.js"></script>
    <script src="∼/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SJD Tool Hire</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Home", "List", "Tool", null, new { returnUrl = Request.Url.PathAndQuery })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SJDToolHire.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Content/dashboard.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker3.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right
        {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SJD Tool Hire</a>
                @Html.Action("Summary", "Cart")
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Help</a></li>
                    <li>
                        @Html.ActionLink("Admin", "Index", "Admin", null, new { returnUrl = Request.Url.PathAndQuery })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="visible-xs" style="margin-top:40px; background-color: transparent">
        @Html.Action("Menu", "Nav", new { horizontalLayout = true })
    </div>
     <div class="row-fluid" style="margin-top:40px; background-color: transparent">
        <div class="col-sm-1 hidden-xs col-md-offset-1">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-md-7">
            @RenderBody()
        </div>
         <div class="col-md-offset-9" style="margin-left:20px">
             <img src="~/Content/Images/husqvarna.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9" style="margin-left:20px">
             <img src="~/Content/Images/makita.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/bosch.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/dewalt.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/honda.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/hilti.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/hitachi.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/ryobi.jpg" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/spacer.png" class="img-thumbnail" style="width:150px; height: auto; opacity:0.0" />
         </div>
         <div class="col-md-offset-9">
             <img src="~/Content/Images/mac.png" class="img-thumbnail" style="width:150px; height: auto" />
         </div>
    </div>
    <script type="text/javascript">
        $(function ()
        { // will trigger when the document is ready
            $(".datepicker").datepicker(
            {
                format: "dd/mm/yyyy",
                autoclose: true,
                todayHighlight: true
            });
            $(".startdate").datepicker(
            {
            }).on('changeDate', function (selected)
            {
                var startDate = new Date(selected.date.valueOf());
                $('.enddate').datepicker('setStartDate', startDate);
                $('#form-start-date').submit();
            }).on('clearDate', function (selected)
            {
                $('.enddate').datepicker('setStartDate', null);
                $('#form-start-date').submit();
            });
            $(".enddate").datepicker(
            {
            }).on('changeDate', function (selected)
            {
                var endDate = new Date(selected.date.valueOf());
                $('.startdate').datepicker('setEndDate', endDate);
                $('#form-end-date').submit();
            }).on('clearDate', function (selected)
            {
                $('.startdate').datepicker('setEndDate', null);
                $('#form-end-date').submit();
            });
        });
    </script>
</body>
</html>